version: "3"

services:
  killing-floor-2-server:
    image: rouhim/killing-floor-2-server
    build:
      context: container-data
      dockerfile: Containerfile
    restart: unless-stopped
    volumes:
      - "./data:/data"
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:27015:27015/udp"
      - "0.0.0.0:18080:8080/tcp"
      - "0.0.0.0:20560:20560/tcp"
    environment:
      KF2_CUSTOM_MAPS: "2054449073"
      KF2_MODS: "2875147606"
      KF2_WEB_ADMIN_ENABLED: "true"
      KF2_WEB_ADMIN_PASSWORD: "Admin"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"