FROM rouhim/steamcmd:latest

# General environment variables
ENV STEAM_APP_ID "232130"
ENV STARTUP_COMMAND "./Binaries/Win64/KFGameSteamServer.bin.x86_64 kf-bioticslab"

# KF2 specific environment variables
ENV KF2_CUSTOM_MAPS ""
ENV KF2_MODS ""
ENV KF2_WEB_ADMIN_ENABLED "false"
ENV KF2_WEB_ADMIN_PASSWORD ""

USER root

# Install kf2 server requirements
RUN apt update && \
    apt upgrade -y && \
    apt install -y curl libcurl4 less

# Disable apt package manager
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

USER $USER

# Install envini
RUN LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/RouHim/envini/releases/latest | \
    sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/') && \
    curl -L -o $USER_HOME/envini https://github.com/RouHim/envini/releases/download/$LATEST_VERSION/envini-$LATEST_VERSION-x86_64 && \
    chmod +x $USER_HOME/envini
COPY --chown=$USER:$USER envini_mapping.ini $USER_HOME/envini_mapping.ini

# Copy pre script, that allows to declarative configure the server
COPY --chown=$USER:$USER pre.sh $USER_HOME/pre.sh
COPY --chown=$USER:$USER configure_custom_maps.sh $USER_HOME/configure_custom_maps.sh

# Expose ports
EXPOSE 7777/udp
EXPOSE 27015/udp
EXPOSE 8080/tcp
EXPOSE 20560/tcp
