FROM rouhim/steamcmd:latest

# General environment variables
ENV STEAM_APP_ID "232130"
ENV STARTUP_COMMAND "./Binaries/Win64/KFGameSteamServer.bin.x86_64 kf-bioticslab"

# KF2 specific environment variables
ENV KF2_CUSTOM_MAPS ""
ENV KF2_MODS ""
ENV KF2_WEB_ADMIN_ENABLED "false"
ENV KF2_WEB_ADMIN_PASSWORD ""

USER root

# Install kf2 server requirements
RUN apt update && \
    apt upgrade -y && \
    apt install -y libcurl4 less

# Disable apt package manager
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

USER $USER

# Copy pre script, that allows to declarative configure the server
COPY pre.sh $USER_HOME/pre.sh
COPY KF2ServerToolCMD $USER_HOME/KF2ServerToolCMD
COPY KFServerToolCMD.ini $USER_HOME/KFServerToolCMD.ini