FROM rouhim/steamcmd:latest

ENV STEAM_APP_ID "232130"
ENV STARTUP_COMMAND "./Binaries/Win64/KFGameSteamServer.bin.x86_64 kf-bioticslab"

USER root

# Install kf2 server requirements
RUN apt update && \
    apt upgrade -y && \
    apt install -y libcurl4

# Disable apt package manager
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

USER $USER